// <auto-generated />
using System;
using Bpm.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bpm.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508020913_AddHrFlows")]
    partial class AddHrFlows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Bpm.Domain.Entities.Audit.ActorResolutionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorRefJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorKind")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedUserIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmitterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmitterUserId");

                    b.HasIndex("Timestamp");

                    b.ToTable("ActorResolutionAudits", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Authz.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Resource")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Authz.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Roles_ScopeFlowCode", "(\"Scope\" = 1 AND \"FlowCode\" IS NULL) OR (\"Scope\" = 2 AND \"FlowCode\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Authz.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeRef")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("RoleId", "PrincipalId", "Scope", "ScopeRef");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Authz.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.HrFlows.HrFlowAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStep")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStep")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "CreatedAt");

                    b.ToTable("HrFlowActions", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.HrFlows.HrFlowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResolvedManagerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("InitiatorUserId", "LastActivityAt");

                    b.HasIndex("ResolvedManagerUserId", "Status");

                    b.ToTable("HrFlowInstances", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "PrincipalId");

                    b.HasIndex("PrincipalId");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.Principal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Principals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.Department", b =>
                {
                    b.HasBaseType("Bpm.Domain.Entities.Org.Principal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HeadUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HeadUserId");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.Group", b =>
                {
                    b.HasBaseType("Bpm.Domain.Entities.Org.Principal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.User", b =>
                {
                    b.HasBaseType("Bpm.Domain.Entities.Org.Principal");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("TEXT");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Authz.RoleAssignment", b =>
                {
                    b.HasOne("Bpm.Domain.Entities.Org.Principal", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpm.Domain.Entities.Authz.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Authz.RolePermission", b =>
                {
                    b.HasOne("Bpm.Domain.Entities.Authz.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpm.Domain.Entities.Authz.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.HrFlows.HrFlowAction", b =>
                {
                    b.HasOne("Bpm.Domain.Entities.HrFlows.HrFlowInstance", "Instance")
                        .WithMany("Actions")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.GroupMember", b =>
                {
                    b.HasOne("Bpm.Domain.Entities.Org.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpm.Domain.Entities.Org.Principal", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.Department", b =>
                {
                    b.HasOne("Bpm.Domain.Entities.Org.User", "Head")
                        .WithMany()
                        .HasForeignKey("HeadUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bpm.Domain.Entities.Org.Principal", null)
                        .WithOne()
                        .HasForeignKey("Bpm.Domain.Entities.Org.Department", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpm.Domain.Entities.Org.Department", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Head");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.Group", b =>
                {
                    b.HasOne("Bpm.Domain.Entities.Org.Principal", null)
                        .WithOne()
                        .HasForeignKey("Bpm.Domain.Entities.Org.Group", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.User", b =>
                {
                    b.HasOne("Bpm.Domain.Entities.Org.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bpm.Domain.Entities.Org.Principal", null)
                        .WithOne()
                        .HasForeignKey("Bpm.Domain.Entities.Org.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpm.Domain.Entities.Org.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Authz.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.HrFlows.HrFlowInstance", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Bpm.Domain.Entities.Org.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
